### ISSUE TITLE
How can I loop through DOM elements?

### ISSUE THREAD

**Issue by brspurri** [newyankeecodeshop/GAJavaScript#10]
Hi there,

This looks to be a great framework which I am trying to use to is max!

I have the following code to grab my document from my `UIWebView` and a subset of all the `div` elements:

```
id document = [webView documentJS];
id myElement = [document getElementsByClassName:@"div"];
```

`myElement` is of the type `GAScriptObject` (as expected), but how can I get information about the `innerHTML` of each `div`? Or more specifically, filter by an attribute?

Ideally, I am trying to get a reference to an element which does not have an id or a name (but I know it's text and a few other attributes). 

Any advice would be super awesome. I'm stuck here.

Cheers,
Brett

**Comment by lukasberns** [comment]
You can do `[myElement valueForKey:@"innerHTML"]` or if you want to do it neatly, you might be able to define a protocol with a `-(NSString*)innerHTML;` method and cast the GAScriptObject to it. Then you can probably use `myElement.innerHTML` (without actually coding anything)

**Comment by lukasberns** [comment]
Apart from that I think you should ask this question on a site like StackOverflow since this is not an "issue"

**Comment by newyankeecodeshop** [comment]
In your code snippet above, `[document getElementsByClassName:@"div"]` would return an HTML collection of elements, so you'll have to do something like this:

```
#import "GAScriptMethodSignatures.h"  // for "[length]" and "[item:]"

id document = [webView documentJS];
id myElements = [document getElementsByTagName(@"div")];

for (NSInteger i = 0; i < [myElements length]; ++i)
{
    id anElement = [myElements item:i];
    NSString *innerHTML = [anElement valueForKey:@"innerHTML"];
} 
```

If you want to get all the DIVs filtering by an attribute, you can use `[document querySelectorAll:@"div[attr=val]"]`. Make sure to try out the query in the Safari Web Inspector first, since it might take some tweaks to get what you want. "querySelectorAll" is really handy and gives jQuery-like access to elements in a single method call.

**Comment by newyankeecodeshop** [comment]
Experimenting with this code helped me find a bug in the NSFastEnumeration implementation inside GAScriptObject. Cool.
