### ISSUE TITLE
Weird issue with GAJavascript.performSelector JS

### ISSUE THREAD

**Issue by chiefy** [newyankeecodeshop/GAJavaScript#6]
So I have narrowed down the issue I am having to trying to communicate from JS back to objC via GAJavascript.performSelector. 

If you take a look at a sample project I created, there is one line that in boxes.html that does a console.log, if I remove that line of code it will perform as desired (appends a h1 to all the webviews that says "I LOVE HTML"), otherwise the h1 is never appended. 

I have worked around this problem for the time being by changing line 152 of ga-js-runtime.js to the following:

```
window.setTimeout(function() { location.replace("ga-js:makeLotsaCalls");  }, 500);
```

Not exactly sure why this is causing an issue in my scenario, any ideas?

[Sample Project](http://dl.dropbox.com/u/91463/webviewtest.zip)

**Comment by newyankeecodeshop** [comment]
I've read posts about how using location.replace can have side-effects on the state of the browser, such as canceling timeouts - it may be that. I've also heard in a podcast with a Google engineer that setting the "src" of a hidden iframe is faster than using location.replace. I was originally resistant to using the iframe technique because I didn't want to make any DOM changes, since I'm not sure if it would break user's scripts in some way. It looks like PhoneGap using the hidden iframe technique though, so I will try that and see if it fixes the issue.

**Comment by newyankeecodeshop** [comment]
Try out this fix - it implements the hidden iframe technique. Also, I discovered a means for calling back into Objective-C synchronously. I commented out the code in ga-js-runtime.js. It seems that by removing and appending the iframe, it causes WebKit to immediately call the UIWebViewDelegate. It's done as part of the iframe element's logic when it's added to a document. I didn't want to change the library's behavior too much, and the async behavior could be useful. I'm not sure how the 10 second limit on JS would be affected, for example. Anyway, let me know if the changes fix your issues. Thanks for the test case!
