### ISSUE TITLE
Create instances of ObjC objects from JS

### ISSUE THREAD

**Issue by lucamaraschi** [newyankeecodeshop/GAJavaScript#8]
I was wondering how is possible to create an instance of a ObjC object from a JS script.

**Comment by newyankeecodeshop** [comment]
There isn't a built-in syntax for doing that. GAJavaScript only allows invoking existing ObjC objects, via "GAJavaScript.performSelector(..)" or by invoking a block set on a JS object using [GAScriptObject setFunction:forKey:].

Can you provide more of an idea of what you want to accomplish?

**Comment by lucamaraschi** [comment]
performSelector executes a void method (selector)...

what I'm trying to accomplish are the 2 following scenarios:
1) Create an instance of an existing ObjC object from a javascript script: for example create an instance of object foo and call a method on it.
2) call a method in the ObjC runtime and get a result back: not only performing a void selector but executing a real invocation and return its result.

**Comment by newyankeecodeshop** [comment]
Those have both been hard to accomplish because the mechanism to invoke Objective-C from JS uses a UIWebViewDelegate callback that is invoked as a side-effect of URL navigation (e.g. location.replace or form.submit()). I believe I found a way to invoke Objective-C synchronously, using an iframe element and removing/adding it to the DOM. However, I haven't needed this and I'm not sure how reliable it is.

An alternative would be to have performSelector() take a callback function that would receive the return value of the Objective-C call. It's something that I haven't gotten around to yet. I might have some time to get to it in the next week or so, but if not, perhaps you or someone in the community could?
